### ISSUE TITLE
Add social sharing for each project.

### ISSUE THREAD

**Issue by acekyd** [acekyd/made-in-nigeria#30]
It should be possible to share these projects and their links to twitter and other social media platforms :)

**Comment by ashinzekene** [comment]
The source files for the site are not available

**Comment by whizkydee** [comment]
Hey @ashinzekene,

Thanks for showing interest, the source files would be available soon. The site is currently undergoing some changes.

In the meanwhile, you can checkout [whizkydee/made-in-nigeria](https://github.com/whizkydee/made-in-nigeria/tree/gh-pages) which is the version under development. You can do a PR there so that we merge all into this.

Thanks.

**Comment by acekyd** [comment]
Solved with da91f91
